name: Release PR

on:
  create:

jobs:
  create-pr:
    name: Create Pull Request
    if: github.event.ref_type == 'branch' && startsWith(github.event.ref, 'release/')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch master branch
        run: git fetch origin master:master

      - name: Extract version from branch name
        id: extract
        run: |
          BRANCH_NAME="${{ github.event.ref }}"
          VERSION="v${BRANCH_NAME#release/}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Ensure diff exists
        run: |
          if git diff --quiet master; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit --allow-empty -m "Release ${{ steps.extract.outputs.version }}"
            git push
          fi

      - name: Create GitHub pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.extract.outputs.version }}
        run: |
          exists=$(gh pr list --head "$GITHUB_REF_NAME" --base master --json number --jq '.[0].number')
          if [ -z "$exists" ]; then
            gh pr create \
              --title "Release $VERSION" \
              --body "" \
              --base master \
              --head "$GITHUB_REF_NAME"
          else
            echo "PR #${exists} already exists"
          fi
